[build]
# The index HTML file to drive the bundling process.
target = "app/index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist"


[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = [
    "app",
    "common",
    "workers",
    "kusama",
    "kusama_people",
    "polkadot",
    "polkadot_people",
    "paseo_asset_hub",
    "paseo_people",
]

[clean]
dist = "dist" # The output dir for all final assets.
cargo = false # Optionally perform a cargo clean.
